version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - PORT=3000
      - NEXT_PUBLIC_BACKEND_URL=http://backend.local:3500

  backend:
    build: ./backend
    ports:
      - "3500:3500"
    environment:
      - PORT=3500
