replicaCount: 1

image:
  repository: raymondgao/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  httpPort: 80

env:
  NEXT_PUBLIC_BACKEND_URL: "http://backend.local:3500"

ingress:
  enabled: true
  host: frontend.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
